server:
  port: 7020

spring:
  redis:
    host: localhost
    port: 6379
    timeout: 6000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
    # 集群
#    cluster:
#      nodes:
#         - localhost:6380
#         - localhost:6381
#         - localhost:6382
#      max-redirects: 3
