spring:
  application:
    name: swagger3.0

server:
  port: 7090

# swagger3.0 配置
# 访问地址：http://localhost:7090/swagger-ui/index.html
swagger:
  enable: true
  applicationName: swagger3.0测试
  applicationVersion: 1.0.0
  applicationDescription: 描述